sudo: required # Required for apt-get build-dep
dist: trusty
language: cpp
compiler: gcc

os:
  - linux
  - osx

env:
  - MUMBLE_QT=qt4 MUMBLE_HOST=x86_64-linux-gnu
  - MUMBLE_QT=qt4 MUMBLE_HOST=x86_64-linux-gnu MUMBLE_NO_PCH=1
  - MUMBLE_QT=qt5 MUMBLE_HOST=x86_64-linux-gnu
  - MUMBLE_QT=qt5 MUMBLE_HOST=x86_64-linux-gnu MUMBLE_NO_PCH=1
  - MUMBLE_QT=qt5 MUMBLE_HOST=i686-w64-mingw32
  - MUMBLE_QT=qt5 MUMBLE_HOST=x86_64-w64-mingw32
  - MUMBLE_QT=qt5 MUMBLE_HOST=x86_64-apple-darwin

matrix:
  exclude:
    - os: linux
      env: MUMBLE_QT=qt5 MUMBLE_HOST=x86_64-apple-darwin
    - os: osx
      env: MUMBLE_QT=qt4 MUMBLE_HOST=x86_64-linux-gnu
    - os: osx
      env: MUMBLE_QT=qt4 MUMBLE_HOST=x86_64-linux-gnu MUMBLE_NO_PCH=1
    - os: osx
      env: MUMBLE_QT=qt5 MUMBLE_HOST=x86_64-linux-gnu
    - os: osx
      env: MUMBLE_QT=qt5 MUMBLE_HOST=x86_64-linux-gnu MUMBLE_NO_PCH=1
    - os: osx
      env: MUMBLE_QT=qt5 MUMBLE_HOST=i686-w64-mingw32
    - os: osx
      env: MUMBLE_QT=qt5 MUMBLE_HOST=x86_64-w64-mingw32

  allow_failures:
    - env: MUMBLE_QT=qt5 MUMBLE_HOST=i686-w64-mingw32
    - env: MUMBLE_QT=qt5 MUMBLE_HOST=x86_64-w64-mingw32

jobs:
  include:
    - stage: Create AppImage
      before_install:
        - sudo add-apt-repository ppa:beineri/opt-qt592-trusty -y
        - sudo apt-get update -qq
      install:
       - sudo apt-get -y install tree qt59base qt59svg qt59translations qt59tools protobuf-compiler libprotobuf-dev libsndfile1-dev libssl-dev libgl1-mesa-dev libasound2-dev libpulse-dev libogg-dev libspeex-dev libspeexdsp-dev libopus-dev libzeroc-ice35-dev ice35-translators ice35-slice libspeechd-dev libboost-dev libboost-python-dev libcap-dev libxi-dev
       - source /opt/qt*/bin/qt*-env.sh
      env:
        - MUMBLE_QT=qt5 MUMBLE_HOST=x86_64-linux-gnu
      script: ./scripts/travis-ci/build_appimage.bash
      after_success:
        - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
        - bash upload.sh ./*.AppImage*

before_install:
    # - ./scripts/travis-ci/before_install.bash
    - true

script:
    # - ./scripts/travis-ci/script.bash
    - true

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
